import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {initializeApp} from 'firebase/app';
import {getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut} from 'firebase/auth';
import './style.css';
const e=import.meta.env;
const ready=Boolean(e.VITE_FIREBASE_API_KEY&&e.VITE_FIREBASE_PROJECT_ID);
const auth=ready?getAuth(initializeApp({apiKey:e.VITE_FIREBASE_API_KEY,authDomain:e.VITE_FIREBASE_AUTH_DOMAIN,projectId:e.VITE_FIREBASE_PROJECT_ID,appId:e.VITE_FIREBASE_APP_ID})):null;
const base=e.VITE_API_BASE_URL?.replace(/\/$/,'')||'/api';
function App(){const[user,setUser]=useState<any>(null);const[allowed,setAllowed]=useState(false);const[data,setData]=useState<any>(null);const[error,setError]=useState('');const[email,setEmail]=useState('');const[password,setPassword]=useState('');
 async function request(path:string,method='GET'){const token=await auth?.currentUser?.getIdToken();const r=await fetch(base+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'}});const j=await r.json();if(!r.ok)throw Error(j.detail||'Request failed');return j;}
 useEffect(()=>{if(!auth)return;return onAuthStateChanged(auth,async u=>{setUser(u);setAllowed(false);setData(null);if(!u)return;const c=await u.getIdTokenResult(true);if(c.claims.admin!==true||!u.emailVerified){setError('A verified administrator account is required.');return;}setAllowed(true);try{setData(await request('/admin/review'));}catch(e:any){setError(e.message);}});},[]);
 async function approve(kind:string,id:string){try{await request('/admin/verify/'+kind+'/'+id,'POST');setData(await request('/admin/review'));}catch(e:any){setError(e.message);}}
 return <div><header><strong>KrishiLink <span>AI</span></strong><b>Administration</b>{user&&<button onClick={()=>auth&&signOut(auth)}>Sign out</button>}</header><main>{!allowed?<section className="login"><span className="label">RESTRICTED WORKSPACE</span><h1>Administrator sign in</h1><p>Review buyer and FPO verification requests.</p>{!ready&&<aside>Administrator authentication is not configured yet.</aside>}{error&&<aside role="alert">{error}</aside>}<form onSubmit={async ev=>{ev.preventDefault();try{if(auth)await signInWithEmailAndPassword(auth,email,password);}catch{setError('Unable to sign in. Check your credentials.');}}}><label>Email<input type="email" required value={email} onChange={x=>setEmail(x.target.value)}/></label><label>Password<input type="password" required value={password} onChange={x=>setPassword(x.target.value)}/></label><button disabled={!ready}>Sign in</button></form></section>:<><h1>Verification queue</h1><p>Verify supporting evidence before approving an organization.</p>{error&&<aside>{error}</aside>}{['buyers','fpos'].map(kind=><section key={kind}><h2>{kind==='buyers'?'Buyer requirements':'FPO profiles'} <span>{data?.[kind]?.length||0}</span></h2>{data?.[kind]?.length?<div className="table"><table><thead><tr><th>Name</th><th>Location</th><th>Contact</th><th>Action</th></tr></thead><tbody>{data[kind].map((r:any)=><tr key={r.id}><td>{r.name||r.company}</td><td>{r.location}</td><td>{r.contact}</td><td><button onClick={()=>approve(kind==='buyers'?'buyer':'fpo',r.id)}>Mark verified</button></td></tr>)}</tbody></table></div>:<p>No pending requests.</p>}</section>)}</>}</main></div>
}
createRoot(document.getElementById('root')!).render(<App/>);
