import {previewId} from '../lib/domain';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {CropPhotos,type CropAttachment} from '../components/CropPhotos';
import {CropPhotoGallery} from '../components/CropPhotoGallery';
import {Link,useOutletContext,useNavigate} from 'react-router-dom';
import {Plus,Sprout,Trash2,Upload,ArrowLeft,ShieldCheck,CheckCircle2} from 'lucide-react';
import {useApp} from '../lib/context';
import {useLanguage} from '../lib/i18n';
import {Panel,Field,Note,Badge,Empty,Modal,Busy} from '../components/ui';
import {crops as cropNames,cropParameters,varieties,gradeGuides,today,dateLabel,type Crop,type CropName} from '../lib/domain';
import {api} from '../lib/api';
export function Crops(){const{crops,setCrops,setNotice}=useApp();const{preview,base}=useOutletContext<any>();const{t}=useLanguage();const[remove,setRemove]=useState<Crop|null>(null);const[error,setError]=useState('');return <><div className="page-heading"><div><span className="eyeline">YOUR PRODUCE</span><h1>{t('My crops')}</h1><p>{t('Keep your crop details ready for the right opportunity.')}</p></div><Link className="btn" to={`${base}/crops/new`}><Plus size={18}/>{t('Add crop')}</Link></div>{error&&<Note tone="error">{error}</Note>}{crops.length?<div className="cards-grid">{crops.map((c:Crop)=><Panel key={c.id} className="crop-card"><div className="card-top"><span className="round-icon"><Sprout/></span><Badge tone="green">{t('Grade')} {c.grade}</Badge></div><h2>{t(c.name)}</h2><p>{c.variety} · {c.location}</p><div className="big-quantity">{c.quantity}<span>qtl</span></div><dl><div><dt>{t('Expected selling date')}</dt><dd>{dateLabel(c.sell_date)}</dd></div><div><dt>{t('Visibility')}</dt><dd>{t(c.public?'Buyer discovery':'Private')}</dd></div></dl><CropPhotoGallery crop={c} preview={preview}/><div className="card-actions"><Link className="text-link" to={`${base}/recommendations?crop=${encodeURIComponent(c.id)}`}>{t('Compare markets')} →</Link><button className="icon-btn" aria-label={'Delete '+c.name} onClick={()=>setRemove(c)}><Trash2 size={17}/></button></div></Panel>)}</div>:<Panel><Empty title="No crops added yet" description="Start with your crop, quantity and grade." action={<Link className="btn" to={`${base}/crops/new`}><Plus size={18}/>{t('Add crop')}</Link>}/></Panel>}{remove&&<Modal title="Delete crop?" onClose={()=>setRemove(null)}><p>{t('This will remove the crop and its photos.')}</p><div className="modal-actions"><button className="btn secondary" onClick={()=>setRemove(null)}>{t('Cancel')}</button><button className="btn danger" onClick={async()=>{try{if(!preview)await api('/crops/'+remove.id,{method:'DELETE'});setCrops(crops.filter((c:Crop)=>c.id!==remove.id));setRemove(null);setNotice(t('Crop removed.'));}catch(e:any){setError(e.message);setRemove(null);}}}>{t('Delete')}</button></div></Modal>}</>}
export function AddCrop(){
 const{t}=useLanguage();const{preview,base,role}=useOutletContext<any>();const{crops,setCrops,setNotice,profile,setSelectedCropId}=useApp();const nav=useNavigate();
 const[name,setName]=useState<CropName>('Cotton'),[variety,setVariety]=useState(varieties.Cotton[0]),[grade,setGrade]=useState('A');
 const[photos,setPhotos]=useState<CropAttachment[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);const savedId=useRef<string|null>(null);const photoRef=useRef(photos);photoRef.current=photos;
 useEffect(()=>()=>{photoRef.current.forEach(p=>URL.revokeObjectURL(p.url));},[]);
 function photoStatus(key:string,update:Partial<CropAttachment>){setPhotos(old=>old.map(p=>p.key===key?{...p,...update}:p));}
 async function submit(e:FormEvent<HTMLFormElement>){
  e.preventDefault();setError('');const data=new FormData(e.currentTarget);const parameters:Record<string,number|string>={};
  for(const p of cropParameters[name])if(data.get(p.key)!==''&&data.get(p.key)!==null)parameters[p.key]=Number(data.get(p.key));
  const payload={name,variety,quantity:Number(data.get('quantity')),grade,parameters,location:String(data.get('location')).trim(),sell_date:String(data.get('date')),notes:String(data.get('notes')),public:data.get('public')==='on',acknowledged:data.get('ack')==='on'};
  setBusy(true);try{
   let crop:Crop;
   if(preview){const encoded=await Promise.all(photos.map(p=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(Error('Photo could not be read. Replace it and retry.'));reader.readAsDataURL(p.file);})));crop={...payload,id:previewId(),photos:encoded};}
   else{
    crop=await api(savedId.current?'/crops/'+savedId.current:'/crops',{method:savedId.current?'PUT':'POST',body:JSON.stringify(payload)});savedId.current=crop.id;
    const ids:string[]=[];
    for(const photo of photos){if(photo.serverId){ids.push(photo.serverId);continue;}photoStatus(photo.key,{status:'uploading'});try{const form=new FormData();form.append('file',photo.file);const uploaded=await api('/crops/'+crop.id+'/photos',{method:'POST',body:form});ids.push(uploaded.id);photoStatus(photo.key,{status:'saved',serverId:uploaded.id});}catch(e){photoStatus(photo.key,{status:'error'});throw e;}}
    crop={...crop,photos:ids};
   }
   setCrops((old:Crop[])=>[...old.filter(c=>c.id!==crop.id),crop]);setSelectedCropId(crop.id);setNotice(t(preview?'Crop added to preview.':'Crop saved.'));nav(`${base}/recommendations?crop=${encodeURIComponent(crop.id)}`);
  }catch(e){setError((e instanceof Error?e.message:'Could not save crop.')+(savedId.current?' Your crop is saved. Retry Save Crop to finish the remaining photos.':''));}finally{setBusy(false);}
 }
 if(role==='buyer')return <Note>{t('Switch to a farmer or FPO account to add crops.')}</Note>;
 return <><Link className="back-link" to={`${base}/crops`}><ArrowLeft size={16}/>{t('My crops')}</Link><div className="page-heading"><div><span className="eyeline">READY FOR YOUR NEXT HARVEST</span><h1>{t('Add a crop')}</h1><p>{t('Tell us about your crop. We will find relevant markets next.')}</p></div><Badge>{t('Self-declared')}</Badge></div>
 <form onSubmit={submit}><div className="form-layout"><div className="stack"><Panel><div className="section-head"><h2><span className="step-number">1</span>{t('Crop details')}</h2></div><fieldset disabled={busy} className="plain-fieldset"><div className="form-grid">
 <Field label="Crop"><select aria-label={t('Crop')} value={name} onChange={e=>{const n=e.target.value as CropName;setName(n);setVariety(varieties[n][0]);setGrade('A');}}>{cropNames.map(c=><option key={c} value={c}>{t(c)}</option>)}</select></Field>
 <Field label="Variety" hint="Choose the variety of this crop."><select required aria-label={t('Variety')} value={variety} onChange={e=>setVariety(e.target.value)}>{varieties[name].map(v=><option key={v}>{v}</option>)}</select></Field>
 <Field label="Quantity (Quintal)" hint="1 quintal = 100 kg"><input required name="quantity" type="number" min="0.01" max="1000000" step="0.01" placeholder="e.g. 50"/></Field>
 <Field label="Location" hint="Village or town, district and state"><input required name="location" minLength={2} maxLength={150} defaultValue={profile?.location||''} placeholder="e.g. Olpad, Surat, Gujarat"/></Field>
 <Field label="Expected selling date"><input required name="date" type="date" min={today()} defaultValue={today()}/></Field></div></fieldset>
 {name==='Rice'&&<Note>{t('Select Rice for milled rice. Paddy is a different commodity and will not be mixed into its market prices.')}</Note>}</Panel>
 <Panel><div className="section-head"><h2><span className="step-number">2</span>{t('Quality & grade')}</h2><Badge tone="amber">{t('Self-declared')}</Badge></div><p className="muted">{t('These descriptions guide your own quality declaration. They are not official AGMARK grades. Market-reported grades are shown separately.')}</p><div className="grade-options">{['A','B','C'].map((g,i)=><button key={g} type="button" disabled={busy} aria-pressed={grade===g} className={grade===g?'selected':''} onClick={()=>setGrade(g)}><div><strong>{t('Grade')} {g}</strong>{grade===g&&<CheckCircle2 size={18}/>}</div><p>{t(gradeGuides[name][i])}</p></button>)}</div>
 <fieldset disabled={busy} className="plain-fieldset"><div className="form-grid" key={name}>{cropParameters[name].map(p=><Field key={name+p.key} label={p.label} hint={p.unit||'Lab measurement'}><input type="number" name={p.key} min="0" max={p.max} step="any" placeholder={t('If measured')}/></Field>)}</div></fieldset><Note>{t('Leave unknown measurements blank. Do not estimate laboratory results.')}</Note></Panel>
 <Panel><div className="section-head"><h2><span className="step-number">3</span>{t('Additional notes')}</h2></div><Field label="Additional notes"><textarea disabled={busy} name="notes" maxLength={2000} rows={3} placeholder={t('Harvest date, packaging, handling or other useful details…')}/></Field><CropPhotos photos={photos} onChange={setPhotos} disabled={busy} onRemove={async p=>{if(p.serverId&&savedId.current)await api(`/crops/${savedId.current}/photos/${p.serverId}`,{method:'DELETE'});}}/>{preview&&photos.length>0&&<small className="muted">{t('Preview photos stay only in this session. Sign in to save them to your account.')}</small>}</Panel></div>
 <aside className="stack sticky-form-aside"><Panel className="quality-guide accuracy-warning"><ShieldCheck size={30}/><h3>{t('Good details build trust.')}</h3><p>{t('Please check your quantity, quality and photos carefully. Buyers rely on these details, and inaccurate information can lead to rejected produce or disputes.')}</p><div className="divider"/><label className="checkbox-row"><input required disabled={busy} type="checkbox" name="ack"/><span>{t('I confirm that these crop details are accurate to the best of my knowledge.')}</span></label><label className="checkbox-row"><input disabled={busy} type="checkbox" name="public"/><span>{t('Show this crop in buyer discovery. My private notes stay private.')}</span></label></Panel>{error&&<Note tone="error">{error}</Note>}<button className="btn full" disabled={busy}>{busy?<Busy/>:<><Plus size={18}/>{t('Save crop')}</>}</button><p className="muted text-small">{t('Next: choose from real market, transport and storage suggestions.')}</p><Link className="btn secondary" to={`${base}/crops`}>{t('Cancel')}</Link></aside></div></form></>;
}
