import {useEffect,useRef,useState} from 'react';
import {Link,useNavigate,useOutletContext} from 'react-router-dom';
import {ArrowRight,RefreshCw,MapPin,Truck,Warehouse,CheckCircle2,Plus} from 'lucide-react';
import {Panel,Field,Note,Badge,Empty,Busy,Source} from '../components/ui';
import {CropSelector} from '../components/CropSelector';
import {useLanguage} from '../lib/i18n';
import {useApp} from '../lib/context';
import {rupee,dateLabel} from '../lib/domain';
import {cropKey,useSelectedCrop,useMarketOptions,type MarketChoice,type MarketOption} from '../lib/marketFlow';
import {buildStaticComparison} from '../lib/staticRecommendations';
export function NetCalculator(){return <Recommendations/>;}
export function Recommendations(){
 const{t}=useLanguage();const{base,preview}=useOutletContext<any>();const nav=useNavigate();const{crops,crop,selectCrop}=useSelectedCrop();const{marketFlow,setMarketFlow,setNotice}=useApp();
 const key=crop?cropKey(crop):'';const flow=marketFlow?.key===key?marketFlow:null;const days=flow?.storageDays||0;const{feed,loading,error,refresh}=useMarketOptions(crop,days);const[nowTick,setNowTick]=useState(Date.now());const[busy,setBusy]=useState(false),[compareError,setCompareError]=useState('');
 useEffect(()=>{const timer=setInterval(()=>setNowTick(Date.now()),15000);return()=>clearInterval(timer);},[]);
 const currentRequest=useRef('');currentRequest.current=key+'|'+feed?.snapshot_id;
 const selections:MarketChoice[]=flow?.snapshotId===feed?.snapshot_id?flow?.selections||[]:[];const expired=flow?.result&&Date.parse(flow.result.expires_at)<=nowTick;const result=!expired&&flow?.snapshotId===feed?.snapshot_id?flow?.result:null;
 useEffect(()=>{setCompareError('');if(feed&&crop){setMarketFlow((previous:any)=>previous?.key===key&&previous.snapshotId===feed.snapshot_id?previous:{key,storageDays:days,snapshotId:feed.snapshot_id,selections:(feed as any).suggested_selections||[],result:null});}},[feed?.snapshot_id,key]);
 function update(next:MarketChoice[]){setCompareError('');setMarketFlow({key,storageDays:days,snapshotId:feed?.snapshot_id,selections:next,result:null});}
 function selectMarket(id:string){if(selections.some(s=>s.market_id===id)){update(selections.filter(s=>s.market_id!==id));return;}if(selections.length>=3){setCompareError('Choose up to 3 markets. Deselect one to add another.');return;}const quote=feed?.services.transport.find(s=>s.market_id===id&&!s.storage_id);update([...selections,{market_id:id,transport_id:days?null:quote?.id||null,storage_id:null}]);}
 function option(id:string,patch:Partial<MarketChoice>){update(selections.map(s=>s.market_id===id?{...s,...patch}:s));}
 async function compare(){
  if(!crop||!feed)return;
  setBusy(true);
  setCompareError('');
  const requestKey=key;
  const snapshotId=feed.snapshot_id;
  try{
    const data=buildStaticComparison(crop,feed,selections,days);
    if(currentRequest.current!==requestKey+'|'+snapshotId)return;
    setMarketFlow((old:any)=>old?.key===requestKey&&old.snapshotId===snapshotId?{...old,result:data}:old);
    nav(`${base}/calculator?crop=${encodeURIComponent(crop.id)}`);
  }catch(e){
    setCompareError(e instanceof Error?e.message:'Comparison could not complete.');
  }finally{
    setBusy(false);
  }
}
 const best=result?.ranking.find((r:any)=>r.id===result.best_market_id);
 return <><div className="page-heading"><div><span className="eyeline">CROP → OPTIONS → YOUR BEST MARKET</span><h1>{t('AI Net Realization')}</h1><p>{t('Compare real mandis after the complete cost of selling your crop.')}</p></div>{crop&&<button className="btn secondary" disabled={loading||busy} onClick={()=>{setMarketFlow({key,storageDays:days,selections:[],result:null});refresh();}}><RefreshCw size={17}/>{t('Refresh suggestions')}</button>}</div>
 {!crop?<Panel><Empty title="Add a crop to find your markets" description="Your crop, variety, grade, quantity and location will guide the suggestions." action={<Link className="btn" to={`${base}/crops/new`}><Plus size={17}/>{t('Add crop')}</Link>}/></Panel>:<>
 <Panel><div className="section-head"><h2><span className="step-number">1</span>{t('Your crop details')}</h2><Badge>{t('Saved crop')}</Badge></div><CropSelector crops={crops} selected={crop} base={base} onSelect={id=>{selectCrop(id);setMarketFlow(null);}}/><div className="storage-preference"><Field label="Storage requirement"><select disabled={busy} value={days?'store':'none'} onChange={e=>{setMarketFlow({key,storageDays:e.target.value==='none'?0:7,selections:[],result:null});}}><option value="none">{t('No storage · direct to market')}</option><option value="store">{t('Storage required')}</option></select></Field>{days>0&&<Field label="Storage duration (days)"><select disabled={busy} value={days} onChange={e=>setMarketFlow({key,storageDays:Number(e.target.value),selections:[],result:null})}>{[1,2,3,5,7,10,14,21,30,60,90].map(n=><option key={n} value={n}>{n}</option>)}</select></Field>}</div></Panel>
 {loading&&<Panel className="mt"><Busy/><p className="muted mt">{t('Finding published prices, nearby markets and suitable service quotes for this crop…')}</p></Panel>}{error&&<Note tone="error">{error}</Note>}
 {feed&&!loading&&<><Panel className="mt"><div className="section-head"><div><h2><span className="step-number">2</span>{t('Select 2–3 markets')}</h2><p>{t('Select transport and, if required, compatible storage for each route.')}</p></div><Badge>{selections.length}/3</Badge></div><p className="muted">{t(feed.message)}</p>{feed.search_limited&&<Note tone="warm">{t('This is a limited nearby search, not a complete list of all mandis. Refresh or refine your saved crop location if a market is missing.')}</Note>}
 {!feed.records.length?<Empty title="No matching live market data" description={feed.message}/>:<div className="market-option-grid">{feed.records.map((market:MarketOption)=>{const selected=selections.find(s=>s.market_id===market.id);const stores=feed.services.storage.filter(s=>s.market_id===market.id);const vehicles=feed.services.transport.filter(s=>s.market_id===market.id&&s.storage_id===(selected?.storage_id||null));const transport=vehicles.find(v=>v.id===selected?.transport_id);const storage=stores.find(v=>v.id===selected?.storage_id);return <section key={market.id} className={'market-option '+(selected?'chosen':'')}><label className="market-option-title"><input type="checkbox" checked={!!selected} disabled={busy} onChange={()=>selectMarket(market.id)}/><span><strong>{market.market}</strong><small>{market.district}, {market.state}</small></span><b>{rupee(market.price)}<small>/ qtl</small></b></label><div className="market-facts"><span><MapPin size={14}/>{market.distance_km==null?t('Road distance unavailable'):market.distance_km+' km · '+t('Estimated')}</span><span>{market.variety||t('Variety not reported')} · {t('Reported grade')}: {market.grade||t('Not reported')}</span><span>{t('Data date')}: {dateLabel(market.date)} · {t(market.variety_match)}</span><span>{t('Grade compatibility')}: {(market as any).grade_verified?t('Verified'):t('Unverified')}</span><span>{t('AI timing trend')}: {(market as any).ai_trend?.status==='estimated'?`${(market as any).ai_trend.signal} · ${(market as any).ai_trend.change_pct}%`:t('Not validated')}</span></div>{!(market as any).grade_verified&&<Note tone="warm">{t('Farmer grade')} {crop.grade} · {t('Reported grade')}: {market.grade||t('Not reported')}. {t('This market stays unconfirmed for Net Realization until A/B/C grade compatibility is verified.')}</Note>}{(market as any).ai_trend?.status==='estimated'&&<Note>{t('AI timing signal')}: <b>{(market as any).ai_trend.signal}</b> · {(market as any).ai_trend.change_pct}% · {t('Market + variety trend only; not a grade-specific sale-price guarantee.')}</Note>}
 {selected&&<div className="option-selectors">{days>0&&<Field label="Storage"><select aria-label={`${market.market} storage`} disabled={busy} value={selected.storage_id||''} onChange={e=>{const sid=e.target.value||null;const vehicle=feed.services.transport.find(s=>s.market_id===market.id&&s.storage_id===sid);option(market.id,{storage_id:sid,transport_id:vehicle?.id||null});}}><option value="">{t(stores.length?'Select compatible storage':'No confirmed compatible storage')}</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name} · {rupee(s.rate_per_quintal_day)}/q/day</option>)}</select></Field>}
 <Field label="Transport vehicle"><select aria-label={`${market.market} transport vehicle`} disabled={busy} value={selected.transport_id||''} onChange={e=>option(market.id,{transport_id:e.target.value||null})}><option value="">{t(vehicles.length?'Select a vehicle':'No current quote for this route')}</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.vehicle} · {v.name} · {v.capacity_quintals} qtl/trip</option>)}</select></Field>
 {transport&&<p className="muted text-small"><Truck size={14}/> {Math.ceil(crop.quantity/transport.capacity_quintals)} {t('trip(s)')} · {rupee(transport.rate_per_km)}/km + {t('quoted fixed costs')}<Source name={transport.source} url={transport.source_url} date={transport.updated_at.slice(0,10)}/></p>}{storage&&<p className="muted text-small"><Warehouse size={14}/> {storage.name} · {t('Minimum billed days')}: {storage.minimum_days}<Source name={storage.source} url={storage.source_url} date={storage.updated_at.slice(0,10)}/></p>}</div>}
 <Source name={market.source} url={market.source_url} date={market.date}/></section>})}</div>}
 <Note>{t('Farmer Grade A/B/C is mandatory for recommendation. FAQ, Local or any other reported mandi grade is not automatically treated as an A/B/C match. Unverified markets can be inspected, but they are not confirmed or ranked as the best Net Realization option.')}</Note><p className="muted text-small">{t(feed.services.message)}</p><div className="panel-bottom"><span className="muted">{t('Prices and costs are fetched automatically. No manual market-price entry.')}</span><button className="btn" disabled={busy||selections.length<2||selections.length>3} onClick={()=>void compare()}>{busy?<Busy/>:<>{t('Compare Net Realization')}<ArrowRight size={17}/></>}</button></div></Panel></>}
 {expired&&<Note tone="warm">{t('These quotes have expired. Refresh suggestions to calculate a new recommendation.')}</Note>}{compareError&&<Note tone="error">{t(compareError)}</Note>}
 {result&&<div className="mt" aria-live="polite"><div className="section-head"><h2><span className="step-number">3</span>{t('AI Net Realization comparison')}</h2><Badge tone="amber">{t('Estimated')}</Badge></div>
 {best?.net_per_quintal<0&&<Note tone="warm">{t('Even the highest estimated return is negative. Selling costs exceed the published sale value.')}</Note>}{best?<Panel className="recommend-result"><Badge tone="green"><CheckCircle2 size={15}/>{t('Best selling recommendation')}</Badge><div><div><h2>{best.market}</h2><p>{best.transport.vehicle} · {best.storage?.name||t('Direct to market')}</p></div><strong>{rupee(best.net_per_quintal)}<small>/ qtl</small></strong></div><p>{t('Total expected realization')}: <b>{rupee(best.total_expected)}</b> · {crop.quantity} qtl</p><p>{t(result.message)}</p></Panel>:<Note tone="warm">{t(result.message)}</Note>}
 <Panel className="mt"><div className="table-wrap"><table className="net-comparison"><caption>{t('All costs below are per quintal unless labelled total. Unknown costs prevent a final recommendation.')}</caption><thead><tr>{['Rank','Market','Market price / q','Distance','Transport / q','Storage / q','Market charges / q','Other costs / q','Net Realization / q','Total expected realization','Data date & source'].map(label=><th key={label}>{t(label)}</th>)}</tr></thead><tbody>{result.ranking.map((r:any)=><tr key={r.id} className={r.id===result.best_market_id?'best-row':''}><td>{r.rank||'—'}</td><td><strong>{r.market}</strong><small>{r.district}, {r.state}</small><small>{r.variety} · {t('Reported grade')}: {r.grade||t('Not reported')}</small></td><td>{rupee(r.price)}</td><td>{r.distance_km==null?'—':r.distance_km+' km'}<small>{t('Estimated')}</small></td><td>{rupee(r.transport_cost)}</td><td>{rupee(r.storage_cost)}</td><td>{rupee(r.market_charges)}</td><td>{rupee(r.other_costs)}</td><td className="price-cell">{rupee(r.net_per_quintal)}</td><td>{rupee(r.total_expected)}</td><td>{dateLabel(r.date)}<Source name={r.source} url={r.source_url}/></td></tr>)}</tbody></table></div>
 <Note>{t(result.price_warning)}</Note>{result.timing_warning&&<Note tone="warm">{t(result.timing_warning)}</Note>}{result.ranking.map((r:any)=><details key={r.id} className="cost-details"><summary>{r.market} · {t('Complete cost breakdown')}</summary>{r.missing.length>0&&<Note tone="warm">{t('Missing')}: {r.missing.map((x:string)=>t(x)).join(', ')}</Note>}<p className="muted">{r.transport?.vehicle||t('Transport quote unavailable')} · {r.storage?.name||t(days?'Storage quote unavailable':'No storage')} · {t(r.distance_note)}</p>{r.breakdown.map((b:any,i:number)=><div className="cost-line" key={i}><div><strong>{b.label}</strong>{b.trips&&<small>{b.trips} {t('trip(s)')} × {b.distance_km} km</small>}{b.billed_days&&<small>{b.billed_days} {t('billed days')}</small>}<Source name={b.source} url={b.source_url} date={b.date.slice(0,10)}/></div><span>{rupee(b.per_quintal)}/q<br/><small>{rupee(b.per_quintal*crop.quantity)} {t('total')}</small></span></div>)}</details>)}</Panel><p className="muted text-small mt">{t('Net Realization = Market Price − Transport − Storage − Market Charges − Other Applicable Costs. This is sale realization, not profit after cultivation costs.')}</p></div>}
 </> }</>;
}
