import {useEffect,useRef,useState} from 'react';
import {Camera,Upload,Trash2,RefreshCw} from 'lucide-react';
import {Modal,Note,Busy} from './ui';
import {useLanguage} from '../lib/i18n';
import {photoMode,validatePhoto,stopCamera,MAX_PHOTOS} from '../lib/photos.mjs';
export type CropAttachment={key:string;file:File;url:string;status:'ready'|'uploading'|'saved'|'error';serverId?:string};
export function CropPhotos({photos,onChange,disabled=false,onRemove}:{photos:CropAttachment[];onChange:(p:CropAttachment[])=>void;disabled?:boolean;onRemove?:(p:CropAttachment)=>Promise<void>}) {
 const {t}=useLanguage();const [mode]=useState(()=>photoMode({userAgent:navigator.userAgent,maxTouchPoints:navigator.maxTouchPoints,coarse:matchMedia('(pointer: coarse)').matches,width:innerWidth}));
 const [error,setError]=useState('');const [camera,setCamera]=useState(false);const [starting,setStarting]=useState(false);const [removing,setRemoving]=useState(false);const [replace,setReplace]=useState<string|null>(null);
 const input=useRef<HTMLInputElement>(null),video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),generation=useRef(0);
 useEffect(()=>()=>{generation.current++;stopCamera(stream.current);},[]);
 function close(){generation.current++;stopCamera(stream.current);stream.current=null;setCamera(false);setStarting(false);}
 async function add(files:File[]){setError('');try{if(photos.length+files.length-(replace?1:0)>MAX_PHOTOS)throw Error('Add up to 3 crop photos.');for(const file of files){await validatePhoto(file);const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>20000000){bitmap.close();throw Error('Photo resolution is too large. Use a photo below 20 megapixels.');}bitmap.close();}
 const old=photos.find(p=>p.key===replace);if(old&&onRemove)await onRemove(old);
 const additions=files.map(file=>({key:crypto.randomUUID?.()||String(Date.now())+file.name,file,url:URL.createObjectURL(file),status:'ready' as const}));
 if(old)URL.revokeObjectURL(old.url);onChange([...photos.filter(p=>p.key!==replace),...additions]);setReplace(null);return true;
 }catch(e){setError(e instanceof Error?e.message:'Photo could not be attached. Please retry.');return false;}}
 async function openCamera(key:string|null=null){setReplace(key);setError('');setStarting(true);setCamera(true);const attempt=++generation.current;try{if(!navigator.mediaDevices?.getUserMedia)throw Error('Camera needs HTTPS and camera permission. Open this page securely and allow your camera.');const next=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1600},height:{ideal:1200}}});if(attempt!==generation.current){stopCamera(next);return;}stream.current=next;if(video.current){video.current.srcObject=next;await video.current.play();}setStarting(false);}catch(e){if(attempt!==generation.current)return;setStarting(false);setError(e instanceof Error&&e.message.startsWith('Camera needs')?e.message:'Camera could not open. Allow camera permission and check that another app is not using it.');stopCamera(stream.current);stream.current=null;}}
 async function capture(){if(!video.current?.videoWidth)return;const canvas=document.createElement('canvas');const ratio=Math.min(1,1600/video.current.videoWidth);canvas.width=Math.round(video.current.videoWidth*ratio);canvas.height=Math.round(video.current.videoHeight*ratio);canvas.getContext('2d')?.drawImage(video.current,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',0.88));if(!blob){setError('Photo capture failed. Please retake it.');return;}if(await add([new File([blob],`crop-${Date.now()}.jpg`,{type:'image/jpeg'})]))close();}
 const choose=(key:string|null=null)=>{setReplace(key);if(mode==='camera')void openCamera(key);else input.current?.click();};
 return <div className="crop-photos"><div className="section-head"><h3>{t('Crop photos')} <small className="muted">({photos.length}/3)</small></h3><span className="muted text-small">JPG, PNG, WebP · 5 MB</span></div>
 {mode==='upload'&&<input ref={input} className="sr-only" aria-label={t('Upload crop photos')} type="file" accept="image/jpeg,image/png,image/webp" multiple={!replace} disabled={disabled} onChange={e=>{const files=Array.from(e.target.files||[]);e.target.value='';if(files.length)void add(files);}}/>}
 <div className="photo-grid">{photos.map(p=><figure key={p.key} className="photo-tile"><img src={p.url} alt={t('Attached crop photo')}/><figcaption><strong title={p.file.name}>{p.file.name}</strong><span role="status">{t(p.status==='saved'?'Uploaded':p.status==='uploading'?'Uploading…':p.status==='error'?'Upload failed — retry Save Crop':'Attached · ready to save')}</span><div><button type="button" className="text-link" disabled={disabled||removing} onClick={()=>choose(p.key)}><RefreshCw size={14}/>{t(mode==='camera'?'Retake':'Replace')}</button><button type="button" className="text-link" disabled={disabled||removing} onClick={async()=>{setRemoving(true);try{await onRemove?.(p);URL.revokeObjectURL(p.url);onChange(photos.filter(x=>x.key!==p.key));}catch(e){setError(e instanceof Error?e.message:'Could not remove photo.');}finally{setRemoving(false);}}}><Trash2 size={14}/>{t('Remove')}</button></div></figcaption></figure>)}</div>
 {photos.length<3&&<button type="button" className="upload-zone full" disabled={disabled||removing} onClick={()=>choose()}>{mode==='camera'?<Camera size={25}/>:<Upload size={25}/>}<strong>{t(mode==='camera'?'Take crop photo':'Upload crop photos')}</strong><span>{t(mode==='camera'?'Use your camera to photograph this crop.':'Choose a photo from your computer.')}</span></button>}
 {error&&!camera&&<Note tone="error">{t(error)}</Note>}
 {camera&&<Modal title="Take crop photo" onClose={close}><video ref={video} playsInline muted autoPlay className="camera-preview"/>{starting&&<Busy/>}{error&&<Note tone="error">{t(error)}</Note>}<div className="modal-actions"><button className="btn secondary" type="button" onClick={close}>{t('Cancel')}</button>{error?<button type="button" className="btn" onClick={()=>void openCamera(replace)}>{t('Retry camera')}</button>:<button className="btn" type="button" disabled={starting} onClick={()=>void capture()}><Camera size={18}/>{t('Capture photo')}</button>}</div></Modal>}
 </div>;
}
