import {useEffect,useState} from 'react';
import {NavLink,Outlet,useLocation,useNavigate,Link,Navigate} from 'react-router-dom';
import {LayoutDashboard,Sprout,BarChart3,Sparkles,Users,Warehouse,Truck,Network,ChartNoAxesCombined,Calculator,HelpCircle,LogOut,Menu,X,MapPin,ArrowUpRight,ClipboardList,ShoppingBag,UserRound} from 'lucide-react';
import {Brand,Language} from './ui';
import {useApp} from '../lib/context';
import {useLanguage} from '../lib/i18n';
import type {Role} from '../lib/domain';
import {roleHome} from '../lib/roles';
const menus={
 farmer:[['dashboard','Dashboard',LayoutDashboard],['crops','My crops',Sprout],['markets','Market prices',BarChart3],['buyers','Buyers',Users],['fpos','FPO network',Network],['transport','Transport',Truck],['storage','Storage',Warehouse],['calculator','Net calculator',Calculator],['recommendations','AI recommendations',Sparkles],['forecasts','Forecasts',ChartNoAxesCombined],['purchases','Sale requests',ShoppingBag],['profile','Profile',UserRound]],
 buyer:[['dashboard','Dashboard',LayoutDashboard],['buyers','Post demand',ClipboardList],['supply','Available farmers',Sprout],['purchases','Purchase history',ShoppingBag],['profile','Profile',UserRound]],
 fpo:[['dashboard','Dashboard',LayoutDashboard],['fpos','Manage storage & services',Warehouse],['requests','Farmer requests',ClipboardList],['profile','Profile',UserRound]]
} as const;
export default function Layout({role}:{role:Role}){const loc=useLocation();const nav=useNavigate();const{t}=useLanguage();const{profile,logout,setDemoRole,notice}=useApp();const[open,setOpen]=useState(false);const preview=loc.pathname.startsWith('/preview');const base=(preview?'/preview':'/app')+'/'+role;const items=menus[role];
 useEffect(()=>{if(preview)setDemoRole(role);},[role,preview]);
 useEffect(()=>{setOpen(false);},[loc.pathname]);
 if(!preview&&profile?.role!==role)return <Navigate to={roleHome(profile?.role||'farmer')} replace/>;
 return <div className={'app-shell role-'+role}>{open&&<button className="sidebar-backdrop" aria-label="Close menu" onClick={()=>setOpen(false)}/>}<aside className={'sidebar '+(open?'open':'')}><div className="sidebar-logo"><Brand/><button className="mobile-only icon-btn" onClick={()=>setOpen(false)} aria-label="Close menu"><X/></button></div><div className="workspace-label">{t(role==='buyer'?'BUYER WORKSPACE':role==='fpo'?'FPO WORKSPACE':'FARMER WORKSPACE')}</div><nav aria-label={t(role==='farmer'?'Farmer navigation':role==='buyer'?'Buyer navigation':'FPO navigation')}>{items.filter(([path])=>path!=='calculator').map(([path,title,Icon])=><NavLink key={path} to={`${base}/${path}`}><Icon size={19}/><span>{t(title)}</span>{path==='recommendations'&&<span className="nav-ai">AI</span>}</NavLink>)}</nav><div className="sidebar-bottom"><div className="small-mission"><Sprout size={24}/><p>{t('Better decisions.')}<br/><strong>{t('Better returns.')}</strong></p></div><NavLink className="support-link" to={`${base}/support`}><HelpCircle size={19}/>{t('Support & sources')}</NavLink><div className="sidebar-account"><Link to={`${base}/profile`}><span className="avatar">{(preview?'P':profile?.name?.[0]||'K').toUpperCase()}</span><div><strong>{preview?t('Preview workspace'):profile?.name}</strong><span>{t(role==='farmer'?'Farmer':role==='buyer'?'Buyer':'FPO')}</span></div></Link><button className="icon-btn" title={t('Sign out')} onClick={async()=>{await logout();nav('/login');}}><LogOut size={18}/></button></div></div></aside><div className="workspace"><header className="topbar"><div className="top-left"><button className="mobile-only icon-btn" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu/></button><div className="breadcrumb">{t(role==='buyer'?'Buyer':role==='fpo'?'FPO':'Farmer')}<span>/</span><strong>{t(items.find(x=>loc.pathname.includes('/'+x[0]))?.[1]||'Support & sources')}</strong></div></div><div className="top-right"><span className="location"><MapPin size={15}/>{profile?.location||'Surat, Gujarat'}</span><Language/><Link className="avatar small" aria-label="Profile" to={`${base}/profile`}>{preview?'P':profile?.name?.[0]||'K'}</Link></div></header>{preview&&<div className="preview-bar"><span><strong>{t('Preview workspace')}</strong> · {t('Changes here last only until you refresh.')}</span><div><select aria-label="Preview role" value={role} onChange={e=>nav(roleHome(e.target.value as Role,true))}><option value="farmer">{t('Farmer')}</option><option value="fpo">{t('FPO')}</option><option value="buyer">{t('Buyer')}</option></select><Link to="/login">{t('Open account')}<ArrowUpRight size={14}/></Link></div></div>}<main className="main-content"><Outlet context={{preview,base,role}}/></main><footer className="workspace-footer"><span>KrishiLink AI <span>by TechMates</span></span><span>{t('Maximize net realization, not just price.')}</span></footer></div>{notice&&<div className="toast" role="status">{notice}</div>}</div>
}
